// @vitest-environment node
// Every theme colour class used in src/ must be generated by Tailwind. Tailwind v4
// ignores tailwind.config.ts, so a token missing from @theme silently renders nothing.
import { readFileSync, readdirSync, statSync } from "node:fs"
import path from "node:path"
import postcss from "postcss"
import tailwind from "@tailwindcss/postcss"
import { describe, expect, it } from "vitest"

const root = path.resolve(__dirname, "../..")
const cssPath = path.join(root, "src/app/globals.css")

const THEME_CLASS =
  /(?<![\w-])(?:bg|text|border|ring|ring-offset|outline|fill|stroke|placeholder|divide)-(?:background|foreground|primary|secondary|destructive|muted|accent|popover|card|border|input|ring)(?:-foreground)?(?:\/\d+)?(?![\w-])/g

function sourceFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const full = path.join(dir, name)
    if (statSync(full).isDirectory()) return name === "__tests__" ? [] : sourceFiles(full)
    return /\.tsx?$/.test(name) ? [full] : []
  })
}

function themeClassesInSource(): string[] {
  const found = new Set<string>()
  for (const file of sourceFiles(path.join(root, "src"))) {
    for (const match of readFileSync(file, "utf8").matchAll(THEME_CLASS)) found.add(match[0])
  }
  return [...found].sort()
}

describe("theme tokens", () => {
  it("generates every theme colour class the components use", async () => {
    const { css } = await postcss([tailwind({ base: root })]).process(readFileSync(cssPath, "utf8"), {
      from: cssPath,
    })
    const used = themeClassesInSource()
    expect(used.length).toBeGreaterThan(0)

    // Used as `bg-accent` (".bg-accent") or behind a variant like `hover:bg-accent` ("\:bg-accent").
    const missing = used.filter((cls) => {
      const escaped = cls.replace("/", "\\/")
      return !css.includes(`.${escaped}`) && !css.includes(`\\:${escaped}`)
    })
    expect(missing).toEqual([])
  }, 60_000)
})
